### ISSUE TITLE
Error "EmptyChannelError" on Vercel

### ISSUE THREAD

**Issue by barbudour** [langchain-ai/langgraphjs#113]
Hi, I'm trying to run the code on Vercel but I'm getting an EmptyChannelError. I am using the code from this [example](https://github.com/langchain-ai/langgraphjs/blob/main/examples/multi_agent/agent_supervisor.ipynb). On local environment everything works fine, but when I run the application in Vercel environment I get this error:
```
 EmptyChannelError: 
    at (node_modules/@langchain/langgraph/dist/channels/last_value.js:39:18)
    at (node_modules/@langchain/langgraph/dist/pregel/index.js:320:30)
    at (node_modules/@langchain/langgraph/dist/pregel/index.js:206:31)
    at (node_modules/@langchain/langgraph/dist/pregel/read.js:51:81)
    at (node_modules/@langchain/langgraph/dist/pregel/read.js:51:60)
    at (node_modules/@langchain/langgraph/dist/pregel/read.js:9:32)
    at (node_modules/@langchain/core/dist/runnables/base.js:1348:44)
    at (node_modules/@langchain/core/dist/runnables/base.js:1346:66) {
  name: 'EmptyChannelError'
}
```

**Comment by sheldonj** [comment]
Im also getting this error in production on vercel, and its working no problem locally. 
tried both using just server actions and a dedicated api route with both nodejs and edge runtimes with the same result.

Happy to try and help with this issue, but need a poke in the right direction to determine what might be the cause of the issue.

**Comment by sheldonj** [comment]
@barbudour  are you using a CheckpointSaver in your implementation?

**Comment by barbudour** [comment]
@sheldonj hi, I don't use CheckpointSaver. I managed to solve the problem, I think there is a bug in the example in the documentation. I changed the following code and it worked in the Vercel environment.

Example:
```typescript
interface AgentStateChannels {
  messages: {
    value: (x: BaseMessage[], y: BaseMessage[]) => BaseMessage[];
    default: () => BaseMessage[];
  };
  next: string;
}

// This defines the agent state
const agentStateChannels: AgentStateChannels = {
  messages: {
    value: (x: BaseMessage[], y: BaseMessage[]) => x.concat(y),
    default: () => [],
  },
  next: 'initialValueForNext', // Replace 'initialValueForNext' with your initial value if needed
};
```

My code:
```typescript
interface AgentStateChannels {
  messages: {
    value: (x: BaseMessage[], y: BaseMessage[]) => BaseMessage[];
    default: () => BaseMessage[];
  };
  next: {
    value: (x: BaseMessage[], y: BaseMessage[]) => BaseMessage[];
    default: () => BaseMessage[];
  };
}

// This defines the agent state
const agentStateChannels: AgentStateChannels = {
  messages: {
    value: (x: BaseMessage[], y: BaseMessage[]) => x.concat(y),
    default: () => [],
},
  next: {
    value: (x: BaseMessage[], y: BaseMessage[]) => x.concat(y),
    default: () => [],
  }
};
```

**Comment by rossanodr** [comment]
> @barbudour are you using a CheckpointSaver in your implementation?

did you managed to solve it?

**Comment by barbudour** [comment]
@rossanodr yes, I was able to solve the problem, I have attached the code to the post above
