### ISSUE TITLE
Incorrect code example in plan and execute example

### ISSUE THREAD

**Issue by yeouchien** [langchain-ai/langgraphjs#122]
this 2 lines are wrong:

1. in `executeStep`
https://github.com/langchain-ai/langgraphjs/blob/c27db2717e3cd26019491bdd60d4c10fd1138d90/examples/plan-and-execute/plan-and-execute.ipynb#L391

this should be `const task = state.plan[0];`

python example ref: https://github.com/langchain-ai/langgraph/blob/0e3c37ba2524bb4c170cec13098161500bdf8eee/examples/plan-and-execute/plan-and-execute.ipynb#L380

2. in workflow addConditionalEdges
https://github.com/langchain-ai/langgraphjs/blob/c27db2717e3cd26019491bdd60d4c10fd1138d90/examples/plan-and-execute/plan-and-execute.ipynb#L457

this should be `false: 'agent',`

python example ref: https://github.com/langchain-ai/langgraph/blob/0e3c37ba2524bb4c170cec13098161500bdf8eee/examples/plan-and-execute/plan-and-execute.ipynb#L442

**Comment by hinthornw** [comment]
Thank you for reporting!
