### ISSUE TITLE
Conditional entry point

### ISSUE THREAD

**Issue by guidorietbroek** [langchain-ai/langgraphjs#123]
Is there a away to create a conditional entry point? In Python this is a function, in TS it seems that it don't exist.

**Comment by hinthornw** [comment]
You can add conditional edges from the `"__start__"` node:

```
builder.addConditionalEdges("__start__", condition, conditionalEdgeMapping)
```

**Comment by guidorietbroek** [comment]
@hinthornw wow, great answer! Didn't know this one exists. Documentation is not yet complete. But I love LangGraph. Thanks for the help!
