### ISSUE TITLE
 Error "EmptyChannelError" on Vercel

### ISSUE THREAD

**Issue by rossanodr** [langchain-ai/langgraphjs#220]
I was following the tutorial https://www.youtube.com/watch?v=BHOTJ_6wRsY&t=1436s
Thie repo works nicely with yarn run dev https://github.com/bracesproul/gen-ui
but it gets errors like [EmptyChannelError] when I try to run it after building or when I try to deploy it on Vercel.

**Comment by cb-bharathvaj** [comment]
+1

**Comment by bharathvaj-ganesan** [comment]
I marked Langraph as external server package in next config file and it solved this EmptyChannelError issue.

https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages

// next.config.js
export default {
  reactStrictMode: true,
  experimental: {
    serverComponentsExternalPackages: ['@langchain/langgraph'],
  },
};

**Comment by rossanodr** [comment]
> I marked Langraph as external server package in next config file and it solved this EmptyChannelError issue.
> 
> https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages
> 
> ```js
> // next.config.js
> export default {
>   reactStrictMode: true,
>   experimental: {
>     serverComponentsExternalPackages: ['@langchain/langgraph'],
>   },
> };
> ```

YOU SAVED MY LIFE
