### ISSUE TITLE
Bug in checkpoint id generation when converting  UUID v1 to UUID v6. 

### ISSUE THREAD

**Issue by chentschel** [langchain-ai/langgraphjs#234]
When the graph is generating a UUID v6 from the starting point the generated id looks like : `6fbb4270-3461-11ef-undefineda0-a9b17340a0aa`. 

Note the 'undefined' in the UUID generated.

This happens because the code used to generate the `id` is called with a negative number. (-1) when the graph does not have previous checkpoints.  

UUID v1 to generate the ID here:  https://github.com/langchain-ai/langgraphjs/blob/main/langgraph/src/checkpoint/id.ts#L30

After the v1 generation, there is a conversion to a UUID v6. It be easy to solve if the use uuid v6, from start. A proposed code bellow. 

```
function uuid6(clockseq: number) {
  // using uuid pkg
  const node = crypto.getRandomValues(new Uint8Array(6));

  return  v6({ node, clockseq });
}
```

@nfcampos ?

**Comment by nfcampos** [comment]
how do we know `v6` function doesn't have the same issue?
\

**Comment by chentschel** [comment]
I tried in a separate script.

Also preferably , it would be good to use v7 instead of v6 . Is that ok
with you?

https://www.ietf.org/archive/id/draft-peabody-dispatch-new-uuid-format-04.html#name-uuid-version-7



CH

**Comment by nfcampos** [comment]
Thanks I'm going to merge the PR linked above. We use v6 as it supports a clock seq field, which we use to ensure checkpoint ids monodically increase with step number
