### ISSUE TITLE
SqliteSaver not available?

### ISSUE THREAD

**Issue by guidorietbroek** [langchain-ai/langgraphjs#257]
I am trying to implement SqliteSaver but it is not yet ready for use? It is not being exported. Can we change this? 

Langgraph v. 0.0.26

**Comment by vbarda** [comment]
@guidorietbroek how are you importing it?

this should work
```js
import { SqliteSaver } from "@langchain/langgraph/checkpoint/sqlite";
```

**Comment by guidorietbroek** [comment]
Tx! But why not included in the index file?

**Comment by jacoblee93** [comment]
Hey @guidorietbroek! The `sqlite` checkpoint requires an extra optional dep. If we included it in the main index file, it'd be required by everyone, which we don't want.

**Comment by guidorietbroek** [comment]
@jacoblee93 yes, totally understandable! Thanks for the quick response. I think it is a very nice addition to the persistent state. So thanks for that as well.
