### ISSUE TITLE
LLM response format structuring while streaming?

### ISSUE THREAD

**Issue by epleaner** [langchain-ai/langgraphjs#267]
Hello,

With LangChain, I am able to quite easily stream LLM responses in a particular format (say, JSON), via JsonOutputFunctionsParser (see [this doc](https://js.langchain.com/v0.1/docs/modules/model_io/output_parsers/types/json_functions/#streaming), with { diff: false}), and get structured JSON every step of the stream.

With LangGraph, I am following [this guide](https://langchain-ai.github.io/langgraphjs/how-tos/respond-in-format/) to ensure the agent responds in JSON format. However, this essentially breaks streaming: the LLM's structured output is not streamed token-by-token, as it is in LangChain – it comes out all at once. If I use [the streamEvents API](https://langchain-ai.github.io/langgraphjs/how-tos/stream-tokens/) in combination with the response tool described in the previous guide to stream LLM output token-by-token, the structure enforcement breaks and I get no output.

Has anyone succeeded in this in LangGraph?

**Comment by jacoblee93** [comment]
Hey @epleaner, thanks for raising this! I've added an example here:

https://langchain-ai.github.io/langgraphjs/how-tos/respond-in-format/#partially-streaming-json

**Comment by epleaner** [comment]
Hey @jacoblee93 , thanks for the response. However, the logs shown in the LangGraph example you've linked do not show structured JSON at every step of the stream. The LangChain example I've linked in my original post does log structured JSON at every step of the stream.

**Comment by jacoblee93** [comment]
> do not show structured JSON at every step of the stream

Ah I see what you're saying, yeah will update later today.

**Comment by jacoblee93** [comment]
Actually, I added it here:

```ts
      // You can also log the raw args instead:
      // console.log(chunk.tool_call_chunks);
```

Can you try that and LMK if it works for you? Keep in mind you may need to do some special parsing of args for points where we can't get fully valid JSON from the chunk.
