### ISSUE TITLE
Implement `Send` API

### ISSUE THREAD

**Issue by moyara-allgood** [langchain-ai/langgraphjs#281]
Hi team!
I saw https://langchain-ai.github.io/langgraph/how-tos/map-reduce/ in python version but could not find the case in JS version. is Send API available or planned soon?

Thanks!

**Comment by bracesproul** [comment]
It is not yet implemented, but high on our to-do list! It should get merged within the next couple weeks. Thank you for your patience on this.

**Comment by bracesproul** [comment]
This has been implemented! https://github.com/langchain-ai/langgraphjs/pull/305
