### ISSUE TITLE
pass graph state or runtime variable to tools

### ISSUE THREAD

**Issue by nnhuyhoang** [langchain-ai/langgraphjs#287]
How can I pass graph state or runtime variable(eg. userID) to tools. I don't want push it to message and rely on tool to extract it. I searched and [pyhon](https://langchain-ai.github.io/langgraph/how-tos/pass-run-time-values-to-tools/) have one, Can we do it in `langgraphjs`?

**Comment by bracesproul** [comment]
In js we have the `configurable` field which is an object that can hold any value. If you pass your custom value via that field when you call `.invoke`/ `.stream` etc you should be able to access it via the `config` arg in any of the sub nodes/runnables.

See [this doc](https://js.langchain.com/v0.2/docs/how_to/tool_runtime/)

let me know if this doesn't provide the context you need

**Comment by nnhuyhoang** [comment]
thank you, it work like a charm
