### ISSUE TITLE
Modifying a graph post compilation; cancelled or allowed? 

### ISSUE THREAD

**Issue by lomasnz** [langchain-ai/langgraphjs#322]
Hi,

I’ve been exploring LangGraphJS and encountered a discrepancy between the documentation and observed behavior regarding graph modifications post-compilation.

According to the [documentation on Graph Migrations](https://langchain-ai.github.io/langgraphjs/concepts/low_level/?h=reduce#graph-migrations), it seems possible to "modify the topology of a graph (e.g., adding or removing nodes) even after the graph is compiled, under certain conditions". However, when attempting to add nodes dynamically after compilation, I receive the warning:

"Adding a node to a graph that has already been compiled. This will not be reflected in the compiled graph."

I may have misunderstood the scope of the documentation, but could you clarify whether post-compilation modifications are supported, and under what conditions they are allowed?

Thank you for your help!
Paul

**Comment by jacoblee93** [comment]
Hey @lomasnz, sorry for missing this!

This is not currently supported in JS - I believe it was a bad docs port from Python. Will remove these lines for now.

**Comment by lomasnz** [comment]
Thanks for clarifying that. I appreciate the response.
