### ISSUE TITLE
Rewoo example wrong array destructure in toolExecution?

### ISSUE THREAD

**Issue by maciejNisztuk** [langchain-ai/langgraphjs#336]
In the Rewoo example code in the toolExecution function in the line:
`  const [, stepName, tool, , toolInputTemplate] = state.steps[_step - 1];
`
the toolInputTemplate variable is assigned the entire matching string, not the tool input. I think the line should look like this:
`const [, stepName, tool, toolInputTemplate] = state.steps[_step - 1];
`

**Comment by bracesproul** [comment]
Thank you for flagging this! I just checked and you're correct. It looks like reason it worked before is the last element in the array it was extracting included the tool input, but also had extra content which was irrelevant. This change should harden the graph for future runs.

[PR here](https://github.com/langchain-ai/langgraphjs/pull/345)
