### ISSUE TITLE
Type error in multi agent collaboration example.

### ISSUE THREAD

**Issue by black-wine** [langchain-ai/langgraphjs#34]
https://github.com/langchain-ai/langgraphjs/blob/main/examples/multi_agent/multi-agent-collaboration.ipynb
I followed this example.

But as you can see in this code, `BaseTool `type is not exist.

https://github.com/langchain-ai/langgraphjs/blob/c9bec21560d77b209a4f4fae397f923cb545f20e/examples/multi_agent/multi-agent-collaboration.ipynb#L62

Could you help me?

There are some types that is not existed or not correct.

**Comment by bracesproul** [comment]
Hey @black-wine thanks for catching this! I just pushed a commit to fix, in the meantime you can use `Tool` instead
