### ISSUE TITLE
Update "Example B" in Reducers doc

### ISSUE THREAD

**Issue by johisa** [langchain-ai/langgraphjs#354]
https://langchain-ai.github.io/langgraphjs/concepts/low_level/#reducers

Example reducer is applied to `foo` in the code snippet, but it's mixing `number` with `string[]`
```
const State = Annotation.Root({
  foo: Annotation<number>({
    reducer: (state: string[], update: string[]) => state.concat(update),
    default: () => [],
  }),
  bar: Annotation<string[]>,
})
```

Also in the following text it's the `bar` prop that implicitly had the custom reducer:

>  If the second node returns{ bar: ["bye"] } then the State would then be { foo: 2, bar: ["hi", "bye"] }. Notice here that the bar key > is updated by concatenating the two arrays together.

It seems to me that the intention was to apply the reducer to `bar`, so the code snippet should reflect this.

I can give it a try and update this if it's okay with the maintainers.

**Comment by bracesproul** [comment]
thank you for flagging this, I quickly put up a PR to fix.
