### ISSUE TITLE
Example in README is not correct.

### ISSUE THREAD

**Issue by zeropaper** [langchain-ai/langgraphjs#38]
I am trying to replicate the example in the README and noticed that the `callModel` is not defined.

https://github.com/langchain-ai/langgraphjs/blob/8ee245f992443c8d7efc0b505451a6cd5cc75504/README.md?plain=1#L239

**Comment by bracesproul** [comment]
Hey, call model is defined on [L202 in the readme](https://github.com/langchain-ai/langgraphjs/blob/8ee245f992443c8d7efc0b505451a6cd5cc75504/README.md?plain=1#L202)
