### ISSUE TITLE
Broken link to dynamic tool creation in README

### ISSUE THREAD

**Issue by zeropaper** [langchain-ai/langgraphjs#39]
As I am trying to replicate the example in the README with a custom tool, I noticed that the link is broken.

https://github.com/langchain-ai/langgraphjs/blob/8ee245f992443c8d7efc0b505451a6cd5cc75504/README.md?plain=1#L57

**Comment by bracesproul** [comment]
Hey, looks like this is just an issue with the main LangChain.js site... 

I've notified the team and we'll be investigating
