### ISSUE TITLE
Broken links in docs pages

### ISSUE THREAD

**Issue by benjamincburns** [langchain-ai/langgraphjs#402]
The "Annotations" link under the "Schema" heading on the [Low Level LangGraph Concepts](https://langchain-ai.github.io/langgraphjs/concepts/low_level/#schema) docs page leads to the following URL, which 404s: https://langchain-ai.github.io/langgraphjs/reference/functions/langgraph.Annotation-1.html

I can't recall any other specific links that are broken like this, but I feel like I've encountered others as well. Do you guys happen to have broken link monitoring set up for your docs? If not, I'd recommend it, as this sort of thing can degrade devs' impressions of the quality of the library/framework.

**Comment by isahers1** [comment]
Thanks for the suggestion! Opened a PR trying to fix this: https://github.com/langchain-ai/langgraphjs/pull/403

**Comment by jacoblee93** [comment]
Fixed in #407, thank you!
