### ISSUE TITLE
ID is not automatically added to HumanMessage used to invoke the graph

### ISSUE THREAD

**Issue by isahers1** [langchain-ai/langgraphjs#425]
This could be annoying if you wanted to update the message later on in the graph because to update a message you need to have its ID.

**Comment by bracesproul** [comment]
cc @jacoblee93 I thought this was alr implemented?

**Comment by jacoblee93** [comment]
Yeah me too but there's something wrong

**Comment by jacoblee93** [comment]
Fixed
