### ISSUE TITLE
I cannot use libs/checkpoint-mongodb as a checkpointer

### ISSUE THREAD

**Issue by alanlozano1** [langchain-ai/langgraphjs#462]
I'm trying to do [this example](https://langchain-ai.github.io/langgraphjs/tutorials/chatbots/customer_support_small_model/) with mongodb as a checkpointer but actually I have this error:
![image](https://github.com/user-attachments/assets/8102139c-ee0d-4977-bcae-1228c456f62a)

**Comment by jacoblee93** [comment]
Can you share what versions you have installed?

The Mongo checkpointer will only work with LangGraph 0.2 and up

**Comment by alanlozano1** [comment]
Thank you @jacoblee93 it works with LangGraph 0.2
