### ISSUE TITLE
How to interrupt a subgraph in langgraphjs

### ISSUE THREAD

**Issue by moyara-allgood** [langchain-ai/langgraphjs#485]
Hi, i'm trying to interrupt subgraph in langgraphjs. I saw https://github.com/langchain-ai/langgraph/issues/1222 and wonder if you have any timeline/plan to implement in JS?

**Comment by jacoblee93** [comment]
Hey @moyara-allgood, yes this is coming soon!

**Comment by moyara-allgood** [comment]
Thanks @jacoblee93. Let me know if need any help since this blocks us from human in the loop with subgraph.

**Comment by jacoblee93** [comment]
Still in progress, will update

**Comment by jacoblee93** [comment]
This is now supported!

https://langchain-ai.github.io/langgraphjs/how-tos/subgraphs-manage-state/
