### ISSUE TITLE
Module '"@langchain/langgraph"' has no exported member 'Annotation'

### ISSUE THREAD

**Issue by jiangziyue1219** [langchain-ai/langgraphjs#517]
When I copied the code from the langchain.com, I met the followint error

Module '"@langchain/langgraph"' has no exported member 'Annotation'.

How can I solve this problem? 
<img width="605" alt="image" src="https://github.com/user-attachments/assets/0f8da846-3d02-4e2b-8282-0f24687d71c5">

**Comment by jacoblee93** [comment]
What version of `@langchain/langgraph` do you have installed?

**Comment by jiangziyue1219** [comment]
> What version of `@langchain/langgraph` do you have installed?

0.0.31


And it seems that it is still ok if I don't import 'Annotation' and  don't use Annotation.Root() to define a state. So can I give up using it ?

**Comment by jacoblee93** [comment]
Can you update to latest (0.2.9)?

**Comment by jiangziyue1219** [comment]
> Can you update to latest (0.2.9)?

ok， the problem has been solved when I update the package to 0.2.9. thanks!

**Comment by jiangziyue1219** [comment]
And what  should I do and how to write if I want to limit the type of a defined state using interface?

**Comment by jacoblee93** [comment]
Maybe this is helpful?

https://langchain-ai.github.io/langgraphjs/how-tos/define-state/

**Comment by jiangziyue1219** [comment]
thanks, but it isn't helpful

**Comment by jacoblee93** [comment]
Can you share code shortly exactly what you're trying to do?
