### ISSUE TITLE
createReactAgent no longer works with ChatAnthropic

### ISSUE THREAD

**Issue by Pckool** [langchain-ai/langgraphjs#519]
I'm using createReactAgent, and when I pass an OpenAI model it works fine, but when I pass an anthropic model, the model never get's the messages passed to the agent graph, even though it's there on the top level of the trace. Once it get's into the `RunnableLanbda` scope, the `messages` property is lost somehow? The system message is still there, but the other messages passed are not. I'm on the latest version for all packages:
```json
{
  "@langchain/community": "0.3.2",
  "@langchain/core": "0.3.3",
  "@langchain/langgraph": "0.2.8",
  "@langchain/anthropic": "0.3.3",
  "@langchain/openai": "0.3.2",
  "langchain": "0.3.2",
}

```
Pics of langsmith traces below:
![CleanShot 2024-09-26 at 15 39 10@2x](https://github.com/user-attachments/assets/fc8ff843-bb80-4cea-b23a-09914b5bcc55)
![CleanShot 2024-09-26 at 15 39 54@2x](https://github.com/user-attachments/assets/9ed4a389-be3d-4afc-a57d-d928315200fa)

Here's an example of how I'm calling it:
```ts
export const claude35Sonnet = new ChatAnthropic({
  modelName: 'claude-3-5-sonnet-20240620',
  temperature: 0.45,
  streaming: true,
  anthropicApiKey: env.ANTHROPIC_API_KEY,
});

const prompt = ChatPromptTemplate.fromMessages(
  [
    SystemMessagePromptTemplate.fromTemplate(`some custom system instructions`),
  ]
);

const agent = createReactAgent({ 
  llm: model, 
  tools: [
    // imagine a list of tools here
  ], 
  messageModifier: prompt 
});

const res = await agent.invoke({
  messages: [
    ['human', 'some random text, please do something for me AI :)']
  ]
})

```

**Comment by jacoblee93** [comment]
Hey @Pckool, you need to add a `MessagesPlaceholder` to your prompt where the agent will inject messages:

```ts
export const claude35Sonnet = new ChatAnthropic({
  modelName: 'claude-3-5-sonnet-20240620',
  temperature: 0.45,
  streaming: true,
  anthropicApiKey: env.ANTHROPIC_API_KEY,
});

const prompt = ChatPromptTemplate.fromMessages(
  [
    ["system", `some custom system instructions`],
    ["placeholder", "{messages}"],
  ]
);

const agent = createReactAgent({ 
  llm: model, 
  tools: [
    // imagine a list of tools here
  ], 
  messageModifier: prompt 
});

const res = await agent.invoke({
  messages: [
    { role: 'user', content: 'some random text, please do something for me AI :)'}
  ]
})
```

Please reopen if the above doesn't fix it!

**Comment by Pckool** [comment]
Hey! That was the first thing I tried and it throws an error saying `messages` is missing
![CleanShot 2024-09-26 at 16 20 26@2x](https://github.com/user-attachments/assets/82592de4-178a-4d83-8f64-ee9c299e3899)

Here's the traces:
![CleanShot 2024-09-26 at 16 21 14@2x](https://github.com/user-attachments/assets/ae07586c-ff17-464f-a3cb-cf08b172c816)
![CleanShot 2024-09-26 at 16 21 54@2x](https://github.com/user-attachments/assets/40f40737-d458-44b8-9948-6015d0fe5020)

**Comment by Pckool** [comment]
I can't reopen this issue from here, but I created another issue here adding the context above: https://github.com/langchain-ai/langgraphjs/issues/521

**Comment by Pckool** [comment]
Found the issue, it was a silly issue with how I was creating the messages, anthropic couldn't recognize the roles I was giving. Gave the full reason in #521

**Comment by jacoblee93** [comment]
Ah ok great! Glad you figured it out.
