### ISSUE TITLE
RunnableConfig not passed to DynamicTool with ToolNode

### ISSUE THREAD

**Issue by robertszalai** [langchain-ai/langgraphjs#588]
I try to pass `RunnableConfig` to a tool used with `ToolNode`. I create the tool with `tool()` and as I see in the source code if there's no schema or I use a string schema a `DynamicTool` is created instead of `DynamicStructuredTool`. The tool is invoked with `(input, runManager, config)`, but with `DynamicTool` the config is not passed correctly, because it doesn't have a wrapper as with `DynamicStructuredTool`. The result is that the second (config) param in my tool function is undefined.

**Comment by jacoblee93** [comment]
Oof, thanks for the heads up. Will patch in https://github.com/langchain-ai/langchainjs

**Comment by jacoblee93** [comment]
A fix for this is live in `@langchain/core@0.3.11`, thanks again!
