### ISSUE TITLE
Export useful class in order to Create my custom ToolNode

### ISSUE THREAD

**Issue by msalafia** [langchain-ai/langgraphjs#609]
I wanted to develop my own ToolNode with some custom logic but i could not do this because some utility classes and types (like `RunnableCallable`) are not exposed by @langchain/langgraph.

I cannot even extend ToolNode behaviour because the `run` method of `ToolNode` is private.

Can such classes and types be exported? Or maybe provide some guides on how define a custom ToolNode?

**Comment by jacoblee93** [comment]
Hey @msalafia, I can export the additional types to allow for this - to date folks have generally implemented their own executor logic but I don't see any reason why subclassing should be difficult.

We should have a guide for custom tool executors as well.

**Comment by jacoblee93** [comment]
Ok, so actually just checked in and we want to keep `RunnableCallable` an implementation detail. You should just extend `Runnable` in your own code for now.

Will keep the change making `run` `protected` for subclassing though
