### ISSUE TITLE
Typesafe graph.invoke?

### ISSUE THREAD

**Issue by austinm911** [langchain-ai/langgraphjs#628]
As far as I can tell, is there not a way to make the invoke method typesafe with the options argument `await graph.invoke({ key1: value })`?

## Expected Output
```ts
const StateAnnotation = Annotation.Root({
	messages: Annotation<string[]>({
		reducer: (x, y) => x.concat(y),
	}),
})

// Define a new graph
const workflow = new StateGraph(StateAnnotation)

const app = workflow.compile()

const result = await app.invoke({ keyDoesNotExist: 'hi' }) // type error here
```

**Comment by jacoblee93** [comment]
Yeah this would be awesome to add - have a lot of work to do in general on inputs/outputs. Thanks for flagging!

**Comment by anushak18** [comment]
Hi! I am a 4th year student at the University of Toronto studying Computer Science. I’m working with my teammates @khushiDesai, @ashvini8, and @ssumaiyaahmed, who are also 4th year students studying Computer Science at UofT. We would like to take on this issue of making the invoke method typesafe.

**Comment by jacoblee93** [comment]
I think it will be a bit tricky to get right but would love your help!
