### ISSUE TITLE
How to access state in tool function ?

### ISSUE THREAD

**Issue by GaoCan702** [langchain-ai/langgraphjs#630]
I'm trying to access the graph state inside a LangGraph tool function.

**Comment by jacoblee93** [comment]
Hey @GaoCan702, see this guide:

https://langchain-ai.github.io/langgraphjs/how-tos/pass-run-time-values-to-tools/

**Comment by GaoCan702** [comment]
Thank you very much for your response. The import of LangGraphRunnableConfig in the documentation is throwing an error. How can I properly import this LangGraphRunnableConfig?

**Comment by GaoCan702** [comment]
@jacoblee93 Thank you very much for your response. The import of LangGraphRunnableConfig in the documentation is throwing an error. How can I properly import this LangGraphRunnableConfig?

**Comment by jacoblee93** [comment]
Make sure you are on the latest LangGraph version

**Comment by apresmoi** [comment]
Hello, I was trying to do exactly the same, accesing the state from a tool. 

This is not currently working if you are using LangGraph on the UI (browser).

**Comment by benjamincburns** [comment]
@apresmoi  @GaoCan702 just a heads up that you can do `getCurrentTaskInput()` now, and it'll return the same value that was passed into your currently executing node.
