### ISSUE TITLE
Type error on conditional graph compilation

### ISSUE THREAD

**Issue by leSullivan** [langchain-ai/langgraphjs#637]
Argument of type 'LlmAgentName' is not assignable to parameter of type 'LlmAgentName.ORCHESTRATOR | "__start__" | (LlmAgentName.ORCHESTRATOR | "__start__")[]'.ts(2345)

When i compile my graph conditionally i can't set additional edges with the new nodes a add later. Without the typescript as workaround

    compileGraph({ availableAgents }: BaseAgentConfig) {
        const workflow = new StateGraph<GraphState>({
          channels: this.graphStateChannels,
        })
          .addNode(LlmAgentName.ORCHESTRATOR, this.generalistNode.bind(this))
          .addEdge(START, LlmAgentName.ORCHESTRATOR)
          .addConditionalEdges(LlmAgentName.ORCHESTRATOR, this.router);
    
        const agentNodeMap = {
          [LlmAgentName.RETRIEVAL]: this.ragAgent.bind(this),
          ...
        };
    
        availableAgents.forEach((agent: LlmAgentName) => {
          const node = agentNodeMap[agent];
          if (node) {
            workflow.addNode(agent, node);
            workflow.addEdge(
              //Temporarily fix as type checking doesn't account for added nodes after initial setup
              agent as LlmAgentName.ORCHESTRATOR | '__start__',
              LlmAgentName.ORCHESTRATOR,
            );
          }
        });
    
        return workflow.compile();
      }

**Comment by jacoblee93** [comment]
Thanks for raising this - this is by design.

**Comment by YvodeRooij** [comment]
@jacoblee93 can you please elaborate. I keep hitting this error, but I dont understand why?
