### ISSUE TITLE
Browser (and other non-node environment) Support

### ISSUE THREAD

**Issue by gingerhendrix** [langchain-ai/langgraphjs#638]
I'm using LangGraph in a browser extension, but it appears the released version requires node via this method:

https://github.com/langchain-ai/langgraphjs/blob/6657998095cece2f7d48323454474a294fee6b65/libs/langgraph/src/setup/async_local_storage.ts#L1-L8

I've simply commented out calling this function, and otherwise LangGraph seems to be fully functional. 

Can we use  a dynamic import or something to allow released LangGraph to work in a browser-like environment?

**Comment by jacoblee93** [comment]
Hey @gingerhendrix, please see instructions here:

https://langchain-ai.github.io/langgraphjs/how-tos/use-in-web-environments/

A few things to watch out for around nesting and config passing but should work fine!

**Comment by hinthornw** [comment]
https://langchain-ai.github.io/langgraphjs/how-tos/use-in-web-environments/?h=browser
^ does this resolve your issue?

**Comment by hinthornw** [comment]
haha jinx
