### ISSUE TITLE
Example: streaming LLM tokens does not work

### ISSUE THREAD

**Issue by nigel-daniels** [langchain-ai/langgraphjs#667]
I am attempting to stream LLM tokens and used the code demonstrated here:

https://langchain-ai.github.io/langgraphjs/how-tos/stream-tokens/

When I run this code it produces no output, whereas the example suggests I should see the tokens separated by the pipe symbol.

**Comment by jacoblee93** [comment]
As discussed in Slack, this is only available in 0.2.20. Just made a PR that will update docs to reflect this.

**Comment by nigel-daniels** [comment]
Thanks, sorry to raise the issue but discord had been pulled, I just thought the service was down. I only found out about the migration to Slack today :(
