### ISSUE TITLE
How do I run a single node when it's already added to a graph?

### ISSUE THREAD

**Issue by oneWalker** [langchain-ai/langgraphjs#764]
The question is the title, how to trigger a single Node?

**Comment by guidorietbroek** [comment]
This section is for issues. 

You should run nodes depending on the edges. Beginnen with START and ending with END.

**Comment by oneWalker** [comment]
> This section is for issues.
> 
> You should run nodes depending on the edges. Beginnen with START and ending with END.

single node is not the whole graph. There are two concepts.

Its the whole graph that beignning with STAT and endging with END, not single node.

**Comment by jacoblee93** [comment]
You can do:

```ts
await graph.nodes[nodeName].invoke({});
```

This is not yet documented, will close the issue when it is!

**Comment by oneWalker** [comment]
> You can do:
> 
> ```ts
> await graph.nodes[nodeName].invoke({});
> ```
> 
> This is not yet documented, will close the issue when it is!

It works, and thanks a lot for making my codes more clean.
