### ISSUE TITLE
Streaming with LangGraph always outputs 3 duplicate tokens

### ISSUE THREAD

**Issue by NERLOE** [langchain-ai/langgraphjs#78]
When streaming a graph, it always outputs the same tokens in the for-loop exactly 3 times for some reason?
There is no way to differentiate the output chunks other than making a check to only save every third token, but that seems like a quirky fix... 

Here is a CodeSandbox link to see an example:
https://codesandbox.io/p/devbox/confident-cookies-54xwlr?file=index.ts

<img width="854" alt="Skærmbillede 2024-02-28 kl  21 34 29" src="https://github.com/langchain-ai/langgraphjs/assets/32075361/bb77b5c5-d0ec-4498-a263-6ac829fc17f0">

**Comment by bracesproul** [comment]
Hey @NERLOE I just copied & pasted this into a .ts file (I didn't run in the code sandbox you linked) but didn't modify any code and my result logged this:
```
result Hello! I'm just a computer program, so I don't have feelings, but I'm here to help you. How can I assist you today?
```

Are you running the latest version of everything?

**Comment by NERLOE** [comment]
Weird... I should be running the latest versions... This is the package.json dependencies on the CodeSandbox... I also have a local dev environment where it does the same...?

<img width="392" alt="Skærmbillede 2024-03-01 kl  08 24 45" src="https://github.com/langchain-ai/langgraphjs/assets/32075361/cae0471b-0f51-4b4c-b2ff-7edfd63e4401">

**Comment by bracesproul** [comment]
Could you push up a repo which I can clone to reproduce? Kinda hard to debug in code sandbox.
Thanks

**Comment by NERLOE** [comment]
Here you go, I have reproduced the bug in this repo:
https://github.com/NERLOE/langchain-bug

**Comment by bracesproul** [comment]
Hey @NERLOE I just cloned and was able to reproduce. Then I bumped the langchain deps:
```json
"dependencies": {
  "@langchain/core": "0.1.41",
  "@langchain/langgraph": "0.0.10",
  "@langchain/openai": "0.0.16"
}
```
and the error stopped occurring. Can you confirm on your end?

**Comment by NERLOE** [comment]
Hey @bracesproul I just tried updating to the following dependencies, and I still get the error:
```json
  "dependencies": {
    "@langchain/core": "0.1.42",
    "@langchain/langgraph": "0.0.10",
    "@langchain/openai": "0.0.16",
   }
```

I have updated the GitHub repo as well, with the updated dependencies.... But this is still the output I get:
<img width="1363" alt="Skærmbillede 2024-03-06 kl  11 00 23" src="https://github.com/langchain-ai/langgraphjs/assets/32075361/54b83388-40d7-43fa-b8a4-2d1a5367b98a">

**Comment by bracesproul** [comment]
I just re-cloned and it worked for me. I would try deleting your node modules folder?

**Comment by NERLOE** [comment]
Just tried this:
1. Deleted node_modules and yarn.lock and reinstalled with yarn, then it suddenly worked. 
2. Then I deleted the node_modules and yarn.lock again to try installing with pnpm, and then it didn't work. 
3. Then I tried installing with yarn again, and now I can't get it to work... 

I've tried deleting and re-installing many times now, and can't get it to work anymore.

**Comment by iliskhan** [comment]
I had the same problem, but downgrading **@langchain/core** to **0.1.14** helped. At the moment I have such dependencies:
`
"dependencies": {
        "@langchain/community": "^0.0.38",
        "@langchain/core": "^0.1.41",
        "@langchain/langgraph": "^0.0.10",
        "@langchain/openai": "^0.0.20"
}
`

**Comment by davidfant** [comment]
@jacoblee93 @bracesproul this issue can prob be closed. i think it was the same thing i ran into earlier
https://github.com/langchain-ai/langchainjs/pull/4834/files
