### ISSUE TITLE
Skipping write for channel undefined:inbox which has no readers

### ISSUE THREAD

**Issue by chizm** [langchain-ai/langgraphjs#79]
Skipping write for channel undefined:inbox which has no readers

**Comment by chizm** [comment]
![image](https://github.com/langchain-ai/langgraphjs/assets/148037829/a4cb0c61-ff7a-4a38-873e-4c60c32175d8)

**Comment by chizm** [comment]
addConditionalEdges end  Node does not terminate

**Comment by bracesproul** [comment]
Hey, could you elaborate more on the error you're seeing? Include code that I can copy & paste to reproduce (not a screenshot), exactly where in your code the error is occurring and a full stack trace of the error.

Thank you!

**Comment by bracesproul** [comment]
Hey, going to close this as stale.
