### ISSUE TITLE
Async_hooks cannot be used in browser

### ISSUE THREAD

**Issue by Hehongyuanlove** [langchain-ai/langgraphjs#81]
I'm using [chat_agent_executor_with_function_calling](https://github.com/langchain-ai/langgraphjs/blob/main/examples/chat_agent_executor_with_function_calling/base.ipynb)

The same code deno can run, but react cannot run in the browser

### node -v  
v21.7.0

### expo 
C:\xxxxx\node_modules\@langchain\langgraph\dist\setup\async_local_storage.js:5 Uncaught TypeError: _async_hooks.AsyncLocalStorage is not a constructor
    at initializeAsyncLocalStorageSingleton (C:\xxxxx\node_modules\@langchain\langgraph\dist\setup\async_local_storage.js:5:2)
    at new Pregel (C:\xxxxxt\node_modules\@langchain\langgraph\dist\pregel\index.js:159:51)
    at StateGraph.compile (C:\xxxxx\node_modules\@langchain\langgraph\dist\graph\state.js:90:13)
    at C:\xxxxx\page\tool\index.tsx:164:21
    at loadModuleImplementation (C:\xxxxx\node_modules\metro-runtime\src\polyfills\require.js:282:19)
    at guardedLoadModule (C:\xxxxx\node_modules\metro-runtime\src\polyfills\require.js:182:1)
    at metroRequire (C:\xxxxx\node_modules\metro-runtime\src\polyfills\require.js:91:43)
    at C:\xxxxx\App.js:4:44
    at loadModuleImplementation (C:\xxxxx\node_modules\metro-runtime\src\polyfills\require.js:282:19)
    at guardedLoadModule (C:\xxxxx\node_modules\metro-runtime\src\polyfills\require.js:182:1)

**Comment by bracesproul** [comment]
cc @jacoblee93 related to `AsyncLocalStorage`

**Comment by jacoblee93** [comment]
Oh shoot 😬

**Comment by demchuk-alex** [comment]
Hey @jacoblee93 having the same issue, tring to use langgraphjs in react-native app, and nextjs.
Sorry for nudging is there any news or work arounds ?

**Comment by jacoblee93** [comment]
Thank you for nudging - will try my best to look this week!

**Comment by davidfant** [comment]
@jacoblee93 I started getting this issue after upgrading Langchain core. Before I was using langgraph 0.0.10 successfully with langchain core 0.1.47, but since upgrading to 0.1.51 this started happening

**Comment by demchuk-alex** [comment]
Oh thanks @davidfant you mean do not import like `Regel` type, since `graph.compile()` returns this type ?

**Comment by jacoblee93** [comment]
Yeah exactly that. The solution I'm thinking of is to add a separate Pregel class that doesn't use hooks for web. Only issue is that it's super convenient 😕

**Comment by demchuk-alex** [comment]
Agree @jacoblee93 or pass some param to compile to turn off tracing for web or pass your tracing something like that 👍

**Comment by jacoblee93** [comment]
Sorry when I say tracing it also affects things like `streamEvents` too so we do still want to make sure it's getting populated even if you're not using tracing

**Comment by demchuk-alex** [comment]
@jacoblee93 fair enough 👍

**Comment by demchuk-alex** [comment]
Hey @jacoblee93 sorry for nudging again :) did you have a chance to make it available for web ? Thanks

**Comment by Luiz-N** [comment]
So fair to say lang graph js does not work in the browser currently?

**Comment by fatganz** [comment]
The same thing for Obsidian plugins

**Comment by jacoblee93** [comment]
At present yes. Will update when I can.

**Comment by saficool** [comment]
> At present yes. Will update when I can.

Waiting for your update, I have plane to use langgraphjs in Angular

**Comment by vladtar** [comment]
Has anyone been able to polyfill `node:async_hooks` via a rollup plugin or something similar? For some reason none of them seem to be working for me.

Here is an example rollup config I tried:
```
import terser from '@rollup/plugin-terser';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import copy from 'rollup-plugin-copy';
import styles from "rollup-plugin-styles";
import { polyfillNode } from "esbuild-plugin-polyfill-node";

export default {
	input: 'dist/MyDataHelps.js',
	output: [
		{
			file: 'dist/cdn/MyFile.js',
			format: 'iife',
			exports: 'named',
			name: 'myFileExports'
		}
	],
	plugins: [
		styles({
			minimize: true
		}),
		copy({
			targets: [
				{ src: ['MyDataHelps.css', 'dist/*.d.ts'], dest: ['dist/npm', 'dist/cdn'] },
				{ src: ['package.json', 'LICENSE', 'README.md'], dest: ['dist/npm'] }
			]
		}),
		polyfillNode({
			polyfills: {
				async_hooks: true
			}
		}),
		commonjs(),
		nodeResolve({
			browser: true,
			preferBuiltins: false
		})
	]
};
```

**Comment by bioshazard** [comment]
Whoa did this really got maybe-solved 3 days ago?! Lucky timing for me. Running this in the browser is critical to my design, thank you @jacoblee93 !!

**Comment by jacoblee93** [comment]
Glad the timing was good! Added some docs too: 

https://langchain-ai.github.io/langgraphjs/how-tos/use-in-web-environments/

**Comment by fatganz** [comment]
Thank you for the hard work! @jacoblee93

**Comment by s97712** [comment]
> Glad the timing was good! Added some docs too:
> 
> https://langchain-ai.github.io/langgraphjs/how-tos/use-in-web-environments/

When will it be released?

**Comment by bioshazard** [comment]
> > Glad the timing was good! Added some docs too:
> > https://langchain-ai.github.io/langgraphjs/how-tos/use-in-web-environments/
> 
> When will it be released?

I saw it was already in the latest release

**Comment by bioshazard** [comment]
> > Glad the timing was good! Added some docs too:
> > https://langchain-ai.github.io/langgraphjs/how-tos/use-in-web-environments/
> 
> When will it be released?

I saw it in the release from 3 days ago. 

![Screenshot_20240616-060611](https://github.com/langchain-ai/langgraphjs/assets/5616668/ba44424d-3934-49a4-ad0c-7fd5b67a910f)

**Comment by axe-me** [comment]
I'm trying to use the prebuilt supervisor agent https://www.npmjs.com/package/@langchain/langgraph-supervisor in react native environment. However, the handoff tool use AsyncLocalStorage from the async hooks module to retrieve config, which breaks the build. I tried to fix it with the polyfill mentioned above (https://github.com/langchain-ai/langgraphjs/issues/879#issuecomment-2749252465) still no luck to make it work. 
Is that possible to publish a web version of the prebuilt agent as well?

**Comment by jacoblee93** [comment]
CC @vbarda - I think it should just be a matter of switching the import to `@langchain/langgraph/web` here and making sure we pass config through everywhere:

https://github.com/langchain-ai/langgraphjs/blob/main/libs/langgraph-supervisor/src/supervisor.ts
